generator: admingenerator.generator.doctrine
params:
  model: Manticora\PushNotificationBundle\Entity\MessageGroup
  namespace_prefix: Manticora
  bundle_name: PushNotificationBundle
  fields: ~

builders:
  list:
    params:
      title: List for PushNotificationBundle
      display: ~
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: ~
  new:
    params:
      title: New object for PushNotificationBundle
      display: ~
      actions:
        list: ~
  edit:
    params:
      title: You're editing the object "{{ YourModel.title }}"
      display: ~
      actions:
        list: ~
  delete: ~
