generator: admingenerator.generator.doctrine
params:
  model: Manticora\PushNotificationBundle\Entity\MessageTemplate
  namespace_prefix: Manticora
  bundle_name: PushNotificationBundle
  fields: 
    attributes:
      formType: collection
      addFormOptions:
          type: \Manticora\PushNotificationBundle\Form\MessageAttributeType
          by_reference: false

builders:
  list:
    params:
      title: List for PushNotificationBundle
      display: ~
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: ~
  new:
    params:
      title: New object for PushNotificationBundle
      display: [name, description, attributes]
      actions:
        list: ~
  edit:
    params:
      title: You're editing the object "{{ MessageTemplate.description }}"
      display: [name, description, attributes]
      actions:
        list: ~
  delete: ~
